[package]
name = "pkey_to_address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.15"
hex = "0.4"
sha3 = "0.9"

